name: ci

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Print versions
        run: |
          docker --version
          docker buildx version
  build-all:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images all targets
        shell: bash
        run: |
          echo "Building for ALL_PLATFORMS=${{ env.ALL_PLATFORMS }}"
          docker buildx create --use --name mybuild
          docker buildx bake -f build/build.hcl --set *.platform=${{ env.ALL_PLATFORMS }} #--progress plain
  build-local:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build images current targets
        shell: bash
        run: |
          docker buildx bake -f build/build.hcl --load
          docker images
  test:
    runs-on: ubuntu-latest
    needs:
      - build-local
    steps:
      - name: Test Hello World images
        run: |
          echo "Running test job!"
          docker run -it --rm ${DOCKER_ORG}/hello:${IMAGE_VERSION}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Deploy Hello World images
        run: |
          echo "Todo deploy images to registry"
          echo "My username: ${{ secret.DOCKER_USERNAME }}"
          echo "My password: ${{ secret.DOCKER_PASSWORD }}"
